steps:
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    args:
    - '--bucket=gs://$_CACHE_BUCKET'
    - '--key=resources-$(checksum yarn.lock)'
    
  - name: 'node:10-jessie-slim'
    args: ['yarn', 'install', '--frozen-lockfile']

  - name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
    - '--bucket=gs://$_CACHE_BUCKET'
    - '--key=resources-$(checksum yarn.lock)'
    - '--path=node_modules'
    - '--path=packages/gatsby-theme-pantheon-core/node_modules'
    - '--path=packages/gatsby-theme-pantheon-drupal/node_modules'
    - '--path=packages/gatsby-theme-pantheon-wordpress/node_modules'
    - '--path=gatsby-drupal/node_modules'
    - '--path=gatsby-drupal-dark/node_modules'
    - '--path=gatsby-drupal-shadowing/node_modules'
    - '--path=gatsby-wordpress/node_modules'
    - '--no-clobber'

  - name: 'node:10-jessie-slim'
    entrypoint: "bash"
    args: 
      - '-c'
      - 'touch .env.production && echo "DRUPAL_TOKEN=..." >> .env.production'
    dir: '$_PATH'
  
  - name: 'node:10-jessie-slim'
    args: ['yarn', 'dark-auth-prod']
    env:
    - DRUPAL_URL=$_DRUPAL_URL
    - DRUPAL_AUTH_CLIENT_ID=$_DRUPAL_AUTH_CLIENT_ID
    - GATSBY_URL=$_GATSBY_URL
    - ENABLE_GATSBY_REFRESH_ENDPOINT=$_ENABLE_GATSBY_REFRESH_ENDPOINT
  
  - name: 'gcr.io/$PROJECT_ID/restore_cache'
    args:
    - '--bucket=gs://$_CACHE_BUCKET'
    - '--key=resources-$_PATH'

  - name: 'node:10-jessie-slim'
    args: ['yarn', 'dark-build']
    env:
    - DRUPAL_URL=$_DRUPAL_URL
    - DRUPAL_AUTH_CLIENT_ID=$_DRUPAL_AUTH_CLIENT_ID
    - GATSBY_URL=$_GATSBY_URL
    - ENABLE_GATSBY_REFRESH_ENDPOINT=$_ENABLE_GATSBY_REFRESH_ENDPOINT
    - CI=true
    - GATSBY_CPU_COUNT=8

  - name: 'gcr.io/$PROJECT_ID/save_cache'
    args:
    - '--bucket=gs://$_CACHE_BUCKET'
    - '--key=resources-$_PATH'
    - '--path=$_PATH/public'
    - '--path=$_PATH/.cache'
  
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting:$_FIREBASE_TARGET', '--token', '$_FIREBASE_TOKEN']

options:
  machineType: 'N1_HIGHCPU_8'

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   entrypoint: "bash"
  #   args: ["-c", "gsutil mb gs://drupal-dark.static.artifactor.io || exit 0"]

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['defacl', 'ch', '-u', 'AllUsers:READER', 'gs://drupal-dark.static.artifactor.io']

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://drupal-dark.static.artifactor.io']
  #   dir: 'gatsby-drupal-dark/public'

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://drupal-dark.static.artifactor.io']
  

    