steps:
  - name: 'node:10-jessie'
    args: ['yarn', 'install']

  - name: 'node:10-jessie'
    entrypoint: "bash"
    args: 
      - '-c'
      - 'touch .env.production && echo "DRUPAL_TOKEN=..." >> .env.production'
    dir: '$_PATH'
  
  - name: 'node:10-jessie'
    args: ['yarn', 'dark-auth-prod']
    env:
    - DRUPAL_URL=$_DRUPAL_URL
    - DRUPAL_AUTH_CLIENT_ID=$_DRUPAL_AUTH_CLIENT_ID
    - GATSBY_URL=$_GATSBY_URL
    - ENABLE_GATSBY_REFRESH_ENDPOINT=$_ENABLE_GATSBY_REFRESH_ENDPOINT

  - name: 'node:10-jessie'
    args: ['yarn', 'dark-build']
    env:
    - DRUPAL_URL=$_DRUPAL_URL
    - DRUPAL_AUTH_CLIENT_ID=$_DRUPAL_AUTH_CLIENT_ID
    - GATSBY_URL=$_GATSBY_URL
    - ENABLE_GATSBY_REFRESH_ENDPOINT=$_ENABLE_GATSBY_REFRESH_ENDPOINT
  
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting:$_FIREBASE_TARGET', '--token', '$_FIREBASE_TOKEN']


  # - name: 'gcr.io/cloud-builders/gsutil'
  #   entrypoint: "bash"
  #   args: ["-c", "gsutil mb gs://drupal-dark.static.artifactor.io || exit 0"]

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['defacl', 'ch', '-u', 'AllUsers:READER', 'gs://drupal-dark.static.artifactor.io']

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://drupal-dark.static.artifactor.io']
  #   dir: 'gatsby-drupal-dark/public'

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://drupal-dark.static.artifactor.io']
  

    